shell:
    program: /usr/bin/zsh

window:
    title: Alacritty

    opacity: 0.90

    padding:
        x: 6
        y: 6
    dynamic_padding: false



key_bindings:
    # (Windows, Linux, and BSD only)
  - { key: V,         mods: Control|Shift, action: Paste                       }
  - { key: C,         mods: Control|Shift, action: Copy                        }
  - { key: Insert,    mods: Shift,         action: PasteSelection              }
  - { key: Key0,      mods: Control,       action: ResetFontSize               }
  - { key: Equals,    mods: Control,       action: IncreaseFontSize            }
  - { key: Plus,      mods: Control,       action: IncreaseFontSize            }
  - { key: Minus,     mods: Control,       action: DecreaseFontSize            }
  - { key: F11,       mods: None,          action: ToggleFullscreen            }
  - { key: Paste,     mods: None,          action: Paste                       }
  - { key: Copy,      mods: None,          action: Copy                        }
  - { key: L,         mods: Control,       action: ClearLogNotice              }
  - { key: L,         mods: Control,       chars: "\x0c"                       }
  - { key: PageUp,    mods: None,          action: ScrollPageUp,   mode: ~Alt  }
  - { key: PageDown,  mods: None,          action: ScrollPageDown, mode: ~Alt  }
  - { key: Home,      mods: Shift,         action: ScrollToTop,    mode: ~Alt  }
  - { key: End,       mods: Shift,         action: ScrollToBottom, mode: ~Alt  }



 # Font configuration (changes require restart)
font:
  # Normal (roman) font face
  normal:
    family: Anonymous Pro
    style: Regular

  # Bold font face
  bold:
    family: Anonymous Pro
    style: Bold

  # Italic font face
  italic:
    family: Anonymous Pro
    style: Italic

  # Bold italic font face
  bold_italic:
    family: Anonymous Pro
    style: Bold Italic

  # Point size
  size: 14.0
